package domains;

public enum Profession {
        
    ACOUGUEIRO ("Açougueiro"),
    ACUMPURISTA ("Acumpurista"),
    ADESTRADOR ("Adestrador/Tratador de Animais/Treinador de Animais"),
    ADMINISTRADOR ("Administrador"),
    ADVOGADO ("Advogado"),
    AEROVIARIO ("Aeroviario/Empregado de Aeroporto"),
    AFIADOR ("Afiador"),
    AGENCIADOR_DE_PROPAGANDA ("Agenciador de Propaganda"),
    AGENCIADOR_CARGAS_TRANSPORTES ("Agenciador de Serv."),
    AGENTE_ADMINISTRATIVO ("Agente Administrativo"),
    AGENTE_DE_COMPRA_VENDA ("Agente de Compra e Venda"),
    AGENTE_DE_SERVICOS_FUNERARIOS ("Agente de Serviços Funerarios"),
    AGENTE_DE_VIAGEM ("Agente de viagem/Agente de turismo/Operador de turismo"),
    AGRONOMO ("Agronomo"),
    AJUDANTE_GERAL ("Ajudante Geral"),
    AJUSTADOR_RETIFICADOR ("Ajustador/Retificador"),
    ALFAIATE ("Alfaiate"),
    AMBULANTES ("Ambulantes(Camelo,Pipoqueiro,etc)"),
    ANALISTA_RECURSOS_HUMANOS ("Analista de Cargos/Recursos Humanos etc"),
    ANALISTA_CREDITO_E_COBRANCA ("Analista de Cred/Cad/Cobr/Garant/Inf etc"),
    ANALISTA_CUSTOS_PROJ_SERV_ECONOMIA ("Analista de Custos/Proj/Serv/Economia etc"),
    ANALISTA_PRODUCAO_CRONOALISTA ("Analista de Producao/Cronoalista"),
    ANALISTA_SISTEMAS ("Analista de Sistemas"),
    APOSENTADO ("Aposentado(exceto funcionario publico)"),
    ARBITRO_DE_ESPORTES ("Arbitro de Esportes"),
    ARMADOR_DE_FERRAGENS ("Armador de Ferragens"),
    ARMEIRO ("Armeiro"),
    ARQUEOLOGO ("Arqueologo"),
    ARQUITETO ("Arquiteto"),
    ARQUIVISTA ("Arquivista"),
    ARTESAO ("Artesao"),
    ARTISTA_PLASTICO ("Artista Plastico"),
    ASCENSORISTA ("Ascensorista"),
    ASSISTENTE_SOCIAL ("Assistente Social"),
    ASTRONOMO ("Astronomo"),
    ATLETA ("Atleta Profissional"),
    ATOR ("Ator"),
    ATUARIO ("Atuario"),
    AUDITOR_PUBLICO ("Auditor Publico"),
    AUXILIAR_COZINHA_LIMPEZA_COSTURA_COPA ("Auxiliar Cozinha/Limpeza/Costura/Copa etc"),
    AUXILIAR_DE_ENFERMAGEM_TECNICO ("Auxiliar de Enfermagem/Tecnico de Enfermagem"),
    AUXILIAR_DE_ESCRITORIO ("Auxiliar de Escritorio e Ass."),
    AUXILIAR_DE_LABORATORIO ("Auxiliar de Laboratorio"),
    AUXILIAR_DE_SERVICOS_GERAIS ("Auxiliar de Serviços Gerais"),
    AVALIADOR ("Avaliador"),
    CUIDADOR ("Cuidador"),
    DANCARINO ("Dançarino"),
    BANCARIO ("Bancario"),
    BARBEIRO ("Barbeiro"),
    BARISTA ("Barista/Barman/Barwoman"),
    BIBLIOTECARIO ("Bibliotecario"),
    BILHETEIRO_COBRADOR ("Bilheteiro(Transp/Diversao)/Trocador/Cobrador Transp Passageiro/Caixa"),
    BIOLOGO ("Biologo"),
    BIOMEDICO ("Biomedico"),
    BOLSISTA ("Bolsista"),
    BOMBEIRO_ENCANADOR ("Bombeiro/Encanador"),
    BORRACHEIRO ("Borracheiro"),
    CABELEIREIRO ("Cabeleireiro"),
    CAIXEIRO_VIAJANTE ("Caixeiro-Viajante"),
    CAMAREIRA_ARRUMADEIRA ("Camareira/Arrumadeira"),
    CANTOR ("Cantor"),
    CARGOS_DE_CONFIANCA_COMISSOES ("Cargos de Confiança/Comissoes"),
    CARREGADOR ("Carregador"),
    CARTEIRO ("Carteiro"),
    CARTORARIO ("Cartorario"),
    CASEIRO ("Caseiro"),
    CAVALARICO ("Cavalarico/Ferrador/Tratador de Animais"),
    CENOGRAFO ("Cenografo"),
    CHAVEIRO ("Chaveiro"),
    CHEFE_DA_PRODUCAO ("Chefe da Producao"),
    CHEFE_INTERMEDIARIO ("Chefe Intermediario"),
    COBRADOR_EM_GERAL ("Cobrador em Geral"),
    COMANDANTE_DE_EMBARCACOES ("Comandante de Embarcacoes"),
    COMENTARISTA ("Comentarista"),
    COMISSARIO_DE_BORDO ("Comissario de Bordo"),
    COMPOSITOR ("Compositor"),
    COMUNICOLOGO ("Comunicologo"),
    CONSELHEIRO_TUTELAR ("Conselheiro Tutelar"),
    CONSULTOR_DE_EMPRESAS ("Consultor de Empresas"),
    CONTADOR ("Contador"),
    CONTRAMESTRE ("Contramestre"),
    CONTROLADOR_DE_VOO ("Controlador de Voo"),
    COREOGRAFO ("Coreografo"),
    CORRETOR_EM_GERAL ("Corretor em Geral"),
    CORTADOR ("Cortador"),
    COSTUREIRA ("Costureira/Bordadeira/Cerzideira"),
    COZINHEIRO_CONFEITEIRO_PADEIRO ("Cozinheiro/Confeiteiro/Padeiro"),
    DECORADOR ("Decorador"),
    DEGUSTADOR_VINHO_CAFE ("Degustador(Vinho/Café etc)"),
    DELEGADO_DE_POLICIA ("Delegado de Policia"),
    DEMONSTRADOR ("Demonstrador"),
    DENTISTA_ODONTOLOGO ("Dentista/Odontologo"),
    DEPILADOR ("Depilador"),
    DEPUTADO_ESTADUAL_FEDERAL ("Deputado Estadual/Federal"),
    DESEMBARGADOR ("Desembargador"),
    DESENHISTA ("Desenhista"),
    DESPACHANTE_INCLUSIVE_ADUANEIRO ("Despachante "),
    DETETIVE_INVESTIGADOR ("Detetive/Investigador"),
    DETETIZADOR ("Detetizador"),
    DIGITADOR ("Digitador"),
    DIPLOMATA ("Diplomata"),
    DIRETOR_DE_EMPRESA ("Diretor de Empresa"),
    DIRETOR_DE_ESPETACULOS ("Diretor de Espetaculos"),
    DIRETOR_DE_ESTABELECIMENTO_DE_ENSINO ("Diretor de Estabelecimento de Ensino"),
    ECONOMISTA ("Economista"),
    ELETRICISTA ("Eletricista"),
    EMBALADOR ("Embalador"),
    EMBALSAMADOR ("Embalsamador"),
    EMPREGADA_DOMESTICA ("Empregada domestica"),
    EMPRESARIO_DE_ATLETA ("Empresario de Atleta"),
    ENFERMEIRO ("Enfermeiro"),
    ENGENHEIRO ("Engenheiro"),
    ENTREVISTADOR_CENSO_PESQUISA_PRECOS ("Entrevistador(Censo/Pesquisa/Preços)"),
    ESCRITOR ("Escritor"),
    ESCULTOR ("Escultor"),
    ESOTERICOS_ASTROLOGOS_TAROLOGO_NUMEROLOGO ("Esotericos(Astrologos/Tarologo/Numerologo etc)"),
    ESTATISTICO ("Estatistico"),
    ESTETICISTA ("Esteticista"),
    ESTILISTA_MODELISTA ("Estilista/Modelista"),
    ESTIVADOR ("Estivador"),
    FARMACEUTICO ("Farmaceutico"),
    FAXINEIRO_DIARISTA ("Faxineiro/Diarista"),
    FEIRANTE ("Feirante"),
    FERRAMENTEIRO ("Ferramenteiro"),
    FISCAL ("Fiscal"),
    FISCAL_DE_PRODUCAO ("Fiscal de Producao"),
    FISCAL_SERVICOS_DE_TRANSPORTE ("Fiscal Serviços de Transporte"),
    FISICO ("Fisico"),
    FISIOTERAPEUTA ("Fisioterapeuta"),
    FOGUISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS ("Foguista de Embarcacoes ou Locomotivas"),
    FONOAUDIOLOGO ("Fonoaudiologo"),
    FORCAS_ARMADAS_SOLDADO_MARINHEIRO ("Forças Armadas s"),
    FOTOGRAFO ("Fotografo"),
    FRENTISTA_TRABALHADOR_DE_POSTO_DE_GASOLINA ("Frentista/Trabalhador de posto de gasolina"),
    FUNCIONARIO_PUBLICO_CIVIL_APOSENTADO ("Funcionario Publico Civil Aposentado"),
    FUNDIDOR ("Fundidor"),
    GARAGISTA ("Garagista"),
    GARCOM_MAITRE ("Garçom/Maitre"),
    GARIMPEIRO ("Garimpeiro"),
    GEOGRAFO ("Geografo"),
    GEOLOGO ("Geologo"),
    GERENTE ("Gerente"),
    GESSISTA ("Gessista"),
    GOVERNADOR_DE_ESTADO ("Governador de Estado"),
    GOVERNANTA ("Governanta"),
    GUIA_TURISTICO ("Guia Turistico"),
    HOSPITAL_TRABALHADORES_EM_GERAL ("Hospital - Trabalhadores em Geral"),
    IMPERMEABILIZADOR ("Impermeabilizador"),
    INSPETOR ("Inspetor"),
    INSPETOR_DE_CONTROLE_DE_QUALIDADE ("Inspetor de Controle de Qualidade"),
    INSTALADOR_DE_GAS_AGUA_ESGOTO ("Instalador de Gas,Agua e Esgoto"),
    INSTRUMENTADOR_CIRURGICO ("Instrumentador Cirurgico"),
    INSTRUMENTISTA ("Instrumentista"),
    INSTRUTOR_DE_AUTOESCOLA ("Instrutor de Autoescola"),
    INSTRUTOR_PROFESSOR_CURSOS_LIVRES ("Instrutor/Professor de Cursos Livres(Ginastica,Ingles,Informatica)"),
    INTERPRETE_TRADUTOR ("Interprete/Tradutor"),
    JARDINEIRO ("Jardineiro"),
    JOALHEIRO ("Joalheiro"),
    JORNALEIRO ("Jornaleiro"),
    JORNALISTA_REPORTER ("Jornalista/Reporter"),
    JUIZ_DE_DIREITO ("Juiz de Direito"),
    LANTERNEIRO ("Lanterneiro"),
    LAVADOR_DE_CARROS_ROUPAS ("Lavador de Carros/Roupas"),
    LEILOEIRO ("Leiloeiro"),
    LEITURISTA ("Leiturista"),
    GARI ("Lixeiro/Gari/Varredor/Coletor de Lixo"),
    LOCUTOR ("Locutor"),
    MANICURE_PEDICURE_PODOLOGO ("Manicure/Pedicure/Podologo"),
    MANOBRISTA_NAO_EMPREGADO_GUARDADOR_DE_CARRO ("Manobrista"),
    MAQUILADOR ("Maquilador"),
    MAQUINISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS ("Maquinista de Embarcacoes ou Locomotivas"),
    MARCENEIRO_CARPINTEIRO ("Marceneiro/Carpinteiro"),
    MARINHEIRO_ASS ("Marinheiro e Ass."),
    MASSAGISTA ("Massagista"),
    MATEMATICO ("Matematico"),
    MECANICO ("Mecanico"),
    MEDICO ("Medico"),
    MEMBRO_DA_DEFENSORIA_PUBLICA ("Membro da Defensoria Publica"),
    MEMBRO_DE_EQUIPE_TECNICA_DE_ESPORTES ("Membro de Equipe tecnica de esportes"),
    MEMBRO_DO_MINISTERIO_PUBLICO ("Membro do Ministerio Publico"),
    MEMBRO_EQUIPE_TECNICA_ESPORTES ("Membro Equipe Técnica Esportes"),
    MESTRE_DE_PRODUCAO ("Mestre de Producao"),
    METEOROLOGISTA ("Meteorologista"),
    MILITAR_EM_GERAL ("Militar em Geral"),
    MILITAR_REFORMADO ("Militar reformado"),
    MINISTRO_DE_ESTADO ("Ministro de Estado"),
    MINISTRO_DE_TRIBUNAL_SUPERIOR ("Ministro de Tribunal Superior"),
    MODELO_DE_MODAS ("Modelo de Modas"),
    MONTADOR ("Montador"),
    MOTORISTA_TRANSPORTE_CARGAS ("Motorista "),
    MOTORISTA_TRANSPORTE_DE_PASSAGEIROS ("Motorista "),
    MOTORISTA_AUTONOMO_TAXISTA_PRINCIPAL ("Motorista autonomo "),
    MUSEOLOGO ("Museologo"),
    MUSICO ("Musico"),
    NUTRICIONISTA ("Nutricionista"),
    OFFICE_BOY_CONTINUO_ENTREGADOR_MOTOBOY ("Office boy/Continuo/Entregador/Motoboy"),
    OFICIAL_DE_FORCAS_AUX_FORCAS_ARMADAS ("Oficial de Forças Aux e Forças Armadas"),
    OFICIAL_DE_JUSTICA ("Oficial de Justiça"),
    OPERADOR_DE_CALDEIRA ("Operador de Caldeira"),
    OPERADOR_DE_CAMERAS_DE_CINEMA_TV ("Operador de Cameras de Cinema e TV"),
    OPERADOR_DE_COMPUTADOR ("Operador de Computador"),
    OPERADOR_DE_GUINDASTE ("Operador de Guindaste"),
    OPERADOR_DE_ILUMINACAO ("Operador de Iluminacao"),
    OPERADOR_DE_MAQUINAS_APARELHOS ("Operador de Maquinas e Aparelhos"),
    OPERADOR_DE_TELEMARKETING ("Operador de Telemarketing"),
    OPERARIO_SEMI_ESPECIALIZADO_PRODUCAO ("Operario Semi-especializado Producao"),
    ORIENTADOR_PEDAGOGICO ("Orientador Pedagogico"),
    OURIVES ("Ourives"),
    PAISAGISTA ("Paisagista"),
    PEDREIRO ("Pedreiro"),
    PENSAO_ALIMENTICIA_PARA_FILHOS ("Pensao alimenticia para filhos"),
    PENSIONISTA ("Pensionista"),
    PERSONAL_TRAINER ("Personal Trainer"),
    PESCADOR ("Pescador"),
    PESQUISADOR_CIENTIFICO ("Pesquisador Cientifico"),
    PILOTO_DE_AERONAVES ("Piloto de Aeronaves"),
    PINTOR ("Pintor"),
    PISCICULTOR ("Piscicultor"),
    PORTEIRO_ZELADOR ("Porteiro/Zelador"),
    PORTUARIO ("Portuario"),
    PREFEITO ("Prefeito"),
    PRENSISTA_ESTAMPADOR ("Prensista/Estampador"),
    PROCURADOR_MEMBROS_DA_PROCURADORIA ("Procurador/Membros da Procuradoria"),
    PRODUTOR_DE_EVENTOS ("Produtor de Eventos(Promoter)/Produtor de Artes em geral"),
    PROFESSOR_AUTONOMO_PARTICULAR ("Professor Autonomo/Particular"),
    PROFESSOR_ENSINO_FUNDAMENTAL_E_MEDIO ("Professor de Ensino Fundamental e Medio"),
    PROFESSOR_ENSINO_SUPERIOR ("Professor de Ensino Superior"),
    PROFESSOR_IDIOMAS ("Professor de Idiomas"),
    PROFISSIONAL_CIRCO_ACROBATA ("Profissional de Circo/Acrobata"),
    PROFISSIONAL_LETRAS_ARTES ("Profissional de Letras e Artes"),
    PROGRAMADOR ("Programador"),
    PROMOTOR_DE_VENDAS ("Promotor de Vendas"),
    PROMOTOR_PUBLICO ("Promotor Publico"),
    PROPRIETARIO_COMERCIAL ("Proprietario de Estabel. Comercial"),
    PROPRIETARIO_INDUSTRIAL ("Proprietario de Estabel. Industrial"),
    PROPRIETARIO_MICROEMPRESA ("Proprietario de Microempresa"),
    PROPRIETARIO_PRESTACAO_SERVICOS ("Proprietario de Estabel. de Prestaçao Serviços"),
    PROPRIETARIO_RURAL_AGRICOLA_FLORESTAL_PECUARI ("Proprietario de Estabel. Rural,Agricola,Florestal,Pecuario"),
    PROTETICO ("Protetico"),
    PSICANALISTA ("Psicologo/Terapeuta/Psicanalista"),
    PSICOTERAPEUTA ("Psicologo/Terapeuta/Psicoterapeuta"),
    PUBLICITARIO ("Publicitario"),
    QUIMICO ("Quimico"),
    RADIALISTA ("Radialista"),
    RECEPCIONISTA ("Recepcionista"),
    RECICLAGEM ("Reciclagem - Trabalhadores em geral"),
    RECREADOR ("Recreador"),
    RELACOES_PUBLICAS ("Relacoes Publicas"),
    RELOJOEIRO ("Relojoeiro"),
    REPRESENTANTE_COMERCIAL ("Representante Comercial"),
    SAPATEIRO ("Sapateiro"),
    SECRETARIA ("Secretaria"),
    SECRETARIO_DE_ESTADO ("Secretario de Estado"),
    SECRETARIO_MUNICIPAL ("Secretario Municipal"),
    SECURITARIO ("Securitario"),
    SEGURANCA_PATRIMONIAL ("Segurança Patrimonial - trabalhadores em geral"),
    SENADOR ("Senador"),
    SERRALHEIRO ("Serralheiro"),
    SERVENTUARIO_DA_JUSTICA ("Serventuario da Justiça"),
    SERVICOS_DE_MANUTENCAO ("Serviços de Manutencao"),
    SOCIOLOGO ("Sociologo"),
    SOLDADO_CORPO_DE_BOMBEIROS ("Soldado Corpo de Bombeiros"),
    SUPERINTENDENTE ("Superintendente"),
    SUPERVISOR ("Supervisor"),
    SUPERVISOR_TECNICO_OPERACIONAL ("Supervisor/Tecnico Operacional"),
    TABELIAO ("Tabeliao"),
    TAPECEIRO ("Tapeceiro"),
    TECNICO_DA_RECEITA_FEDERAL ("Tecnico da Receita Federal"),
    TECNICO_DE_BIOLOGIA ("Tecnico de Biologia"),
    TECNICO_DE_CONTABILIDADE ("Tecnico de Contabilidade"),
    TECNICO_DE_ELETRICIDADE ("Tecnico de Eletricidade"),
    TECNICO_DE_ELETRONICA ("Tecnico de Eletronica"),
    TECNICO_DE_ESTATISTICA ("Tecnico de Estatistica"),
    TECNICO_DE_LABORATORIO ("Tecnico de Laboratorio"),
    TECNICO_DE_MECANICA ("Tecnico de Mecanica"),
    TECNICO_DE_QUIMICA ("Tecnico de Quimica"),
    TECNICO_DE_RADIOLOGIA ("Tecnico de Radiologia"),
    TECNICO_DE_TELECOMUNICACOES ("Tecnico de Telecomunicacoes"),
    TECNICO_EM_AGRONOMIA ("Tecnico em Agronomia"),
    TECNICO_EM_DESPORTOS ("Tecnico em Desportos"),
    TECNICO_EM_EDIFICACOES ("Tecnico em Edificacoes"),
    TECNICO_EM_ELETRONICA ("Tecnico em Eletronica"),
    TECNICO_EM_ESTATISTICA ("Tecnico em Estatistica"),
    TECNICO_EM_FARMACIA ("Tecnico em Farmacia"),
    TECNICO_EM_FINANCAS ("Tecnico em Finanças"),
    TECNICO_EM_INFORMATICA ("Tecnico em Informatica"),
    TECNICO_EM_INSEMINACAO ("Tecnico em Inseminacao"),
    TECNICO_EM_MECANICA ("Tecnico em Mecanica"),
    TECNICO_EM_QUIMICA ("Tecnico em Quimica"),
    TECNICO_EM_RADIOLOGIA ("Tecnico em Radiologia"),
    TECNICO_EM_REFRIGERACAO ("Tecnico em Refrigeracao"),
    TECNICO_EM_TELECOMUNICACOES ("Tecnico em Telecomunicacoes"),
    TECNICO_PROJETISTA ("Tecnico Projetista"),
    TELEFONISTA ("Telefonista"),
    TERAPEUTA_OCUPACIONAL ("Terapeuta Ocupacional"),
    TORNEIRO ("Torneiro"),
    TRABALHADOR_DA_ADMINISTRACAO ("Trabalhador da Administracao"),
    TRABALHADOR_DA_PESCA ("Trabalhador da Pesca"),
    TRABALHADOR_DE_ARTES_GRAFICAS ("Trabalhador de Artes Graficas"),
    TRABALHADOR_DE_CONSTRUCAO_CIVIL ("Trabalhador de Construcao Civil"),
    TRABALHADOR_FABRICACAO_FUMO_CIGARRO_CHARUTOS ("Trabalhador Fabricacao fumo/cigarro/charutos"),
    TRABALHADOR_FABRICACAO_FUMO_CIGARROS_CHARUTOS ("Trabalhador Fabricacao fumo/cigarros/charutos"),
    TRABALHADOR_INDUSTRIAL ("Trabalhador Industrial"),
    TRABALHADOR_RURAL ("Trabalhador Rural"),
    TRABALHADOR_SERV_CONTABCAIXA_ASS ("Trabalhador serv. contab.caixa e ass."),
    TRAINEES ("Trainees"),
    VENDEDOR ("Vendedor"),
    VENDEDOR_PRACISTA ("Vendedor Pracista"),
    VEREADOR ("Vereador"),
    VETERINARIO ("Veterinario"),
    VIDRACEIRO ("Vidraceiro"),
    WEBDESIGNER ("Webdesigner"),
    ZOOTECNISTA ("Zootecnista");
    
    private final String name;

    Profession( String name){
        this.name = name;
    }

    public String getName() {
        return name;
    }

}
