package domains;

public enum CreditStatus {
    PRE_PROCESSAMENTO, 
    PRE_APROVADO, 
    PENDENTE, 
    AGUARDANDO_DOCUMENTOS, 
    EM_ANALISE_MANUAL, 
    EM_ANALISE_OPERACIONAL, 
    EM_ANALISE_DOCUMENTAL, 
    CONTRATADO, 
    LIBERADO, 
    REPROVADO, 
    EXPIRADO
}
